[package]
name = "app"
version = "0.1.0"
authors = []
edition = "2018"

[[bin]]
name = "app"
path = "app/main.rs"

[dependencies]
bitvec = "0.17"
isahc = "0.6"
openssl = { version = "0.10", features = ["vendored"] }
nom = "5.1"
