[package]
name = "gui"
version = "0.1.0"
authors = ["Stephen Crane <sjc@immunant.com>"]
edition = "2018"

[dependencies]
galaxiator = { version = "0.1", path = "../" }
sdl2 = "0.34"
env_logger = "0.7"
image = "0.23"
